//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drastic.Whisper.UI.Translations {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Drastic.Whisper.UI.Translations.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Drastic.Whisper に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャプチャー状態 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CaptureStatus {
            get {
                return ResourceManager.GetString("CaptureStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音声を16000Hzにトランスコードしています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConvertingAudio {
            get {
                return ResourceManager.GetString("ConvertingAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YouTubeからビデオをダウンロードしています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadingYoutubeVideo {
            get {
                return ResourceManager.GetString("DownloadingYoutubeVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFMpegが見つかりませんでした。Drastic.Whisperを実行する前に、FFMpegをインストールしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FFMpegMissingError {
            get {
                return ResourceManager.GetString("FFMpegMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルのパス、URL... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileExamplePlaceholder {
            get {
                return ResourceManager.GetString("FileExamplePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルが見つかりませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileMissingError {
            get {
                return ResourceManager.GetString("FileMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   字幕が生成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateSubtitlesButton {
            get {
                return ResourceManager.GetString("GenerateSubtitlesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   字幕を生成しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GeneratingSubtitles {
            get {
                return ResourceManager.GetString("GeneratingSubtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動 ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LanguageAuto {
            get {
                return ResourceManager.GetString("LanguageAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   言語: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   聴いています... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Listening {
            get {
                return ResourceManager.GetString("Listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   モデルが見つかりませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModelMissingError {
            get {
                return ResourceManager.GetString("ModelMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   モデル: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModelTextLabel {
            get {
                return ResourceManager.GetString("ModelTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルを開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenFileButton {
            get {
                return ResourceManager.GetString("OpenFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   モデルを開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenModelButton {
            get {
                return ResourceManager.GetString("OpenModelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PathTextLabel {
            get {
                return ResourceManager.GetString("PathTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   停止中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Stalled {
            get {
                return ResourceManager.GetString("Stalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   トランスコードに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TranscodeFailedError {
            get {
                return ResourceManager.GetString("TranscodeFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   書き起こす に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TranscribeButtonLabel {
            get {
                return ResourceManager.GetString("TranscribeButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   転写中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Transcribing {
            get {
                return ResourceManager.GetString("Transcribing", resourceCulture);
            }
        }
    }
}
